#!/bin/bash

## Description: (Re-)install the project
## Usage: install [flags]
## Example: ddev install\nddev install --force
## Flags: [{"Name":"force","Shorthand":"f","Usage":"Do not ask any interactive question"}]

# Initialize local variables
FORCE=""
CHOICE=""
SUITES_PATH="suites"

# Functions
reset_suite () {
    local suiteId=$1
    local suitePath=$SUITES_PATH/$suiteId

    echo "Cleaning up '$suiteId'"

    rm -rf $suitePath/config
    rm -rf $suitePath/public
    rm -rf $suitePath/var
    rm -rf $suitePath/vendor
}

reset_suites () {
    for dist in $SUITES_PATH/*/dist.json
    do
        suiteId=$(basename $(dirname $dist));
        reset_suite $suiteId
    done
}

reset_project () {
    echo "Cleaning up project"

    rm -rf config
    rm -rf public
    rm -rf var
    rm -rf vendor
    ddev delete -Oy
}

start_project () {
    ddev start
}

initialize_project () {
    echo "Initializing project"

    ddev composer install --no-interaction
}

initialize_suite () {
    local suiteId=$1
    local suitePath=$SUITES_PATH/$suiteId

    echo "Initializing '$suiteId'"

    ddev composer up -d $suitePath --no-install
}

initialize_suites () {
    ddev composer initialize-suites

    for dist in $SUITES_PATH/*/dist.json
    do
        suiteId=$(basename $(dirname $dist));
        initialize_suite $suiteId
    done
}

setup_project () {
    echo "Setting up project"

    ddev config --project-type=typo3 --docroot=public
    ddev exec touch public/FIRST_INSTALL
}

setup_suite () {
    local suiteId=$1
    local suitePath=$SUITES_PATH/$suiteId
    local dbName=db_${suiteId//-/_}

    echo "Setting up '$suiteId'"
    echo "Installing files with Composer. This may take a while."

    rm -f public/typo3conf/LocalConfiguration.php
    ddev composer ins -d $suitePath >/dev/null 2>&1
    ddev exec "TYPO3_INSTALL_DB_DBNAME=\"$dbName\" TYPO3_INSTALL_SITE_NAME=\"Screenshots suite $suiteId\" composer setup-suite -d $suitePath"
}

setup_suites () {
    for dist in $SUITES_PATH/*/dist.json
    do
        suiteId=$(basename $(dirname $dist));
        setup_suite $suiteId
    done
}

install_project () {
    reset_suites
    reset_project
    start_project
    initialize_project
    initialize_suites
    setup_project
    setup_suites
}

# Parse options and arguments
while :; do
    case ${1:-} in
        -f|--force)
            FORCE=true
            ;;
        *) # Default case: No more options, so break out of the loop.
            break
    esac

    shift
done

# Set user confirmation if force option not set
if [ ! "${FORCE}" = "true" ] ; then
    printf "Warning, this will reset the project and remove all changes. Continue [yes/no]? "
    read CHOICE
fi

if [ "${CHOICE}" = "yes" ] || [ "${FORCE}" = "true" ] ; then
    install_project
fi
