#!/bin/bash

## Description: Sync the packages of the project with the suite instances
## Usage: sync
## Example: ddev sync

# Initialize local variables
FORCE=""
CHOICE=""
SUITES_PATH="suites"
SUITE_ID=""

# Functions
sync_suite () {
    local suiteId=$1
    local suitePath=$SUITES_PATH/$suiteId

    echo "Syncing packages of '$suiteId'"

    ddev composer update -d $suitePath --no-install
}

ddev composer initialize-suites

for dist in $SUITES_PATH/*/dist.json
do
    suiteId=$(basename $(dirname $dist));
    sync_suite $suiteId
done
