services:
  TYPO3\Documentation\Screenshots\Command\CleanUpCommand:
    tags:
      - name: 'console.command'
        command: 'screenshots:cleanup'
  TYPO3\Documentation\Screenshots\Command\FetchSuitesCommand:
    tags:
      - name: 'console.command'
        command: 'screenshots:fetchsuites'
  TYPO3\Documentation\Screenshots\Command\InitCommand:
    tags:
      - name: 'console.command'
        command: 'screenshots:init'
  TYPO3\Documentation\Screenshots\Command\MappingsCommand:
    tags:
      - name: 'console.command'
        command: 'screenshots:mappings'
