#!/bin/bash

## Description: Clean up distribution TYPO3 installations
## Usage: cleanup-distributions <optional-distribution-id>
## Example: cleanup-distributions introduction

DIST_PATH="/var/www/html/suites"

cleanup-distribution() {
    local distName=$1
    local distPath=$DIST_PATH/$distName
    local dbName=db_${distName//-/_}

    echo "Cleaning up '$distName'"

    rm -rf $distPath/config $distPath/public $distPath/var $distPath/vendor
    echo "DROP DATABASE IF EXISTS $dbName;" | mysql -uroot -proot
}

if [[ -z "$1" ]]
then
  for dist in $DIST_PATH/*/dist.json
  do
      distName=$(basename $(dirname $dist));
      if [[ "$distName" == local-* ]]
      then
          echo -e "\e[0;33mSkipping cleanup for '$distName'.\e[0m"
          echo -e "\e[0;33mIf you want to clean this up, execute 'ddev cleanup-distributions $distName'\e[0m"
      else
          cleanup-distribution $distName
      fi
  done
else
    cleanup-distribution $1
fi
