#!/bin/bash

## Description: Fetch all official TYPO3 Documentation manuals
## Usage: fetch-manuals
## Example: fetch-manuals

TARGET_BASEPATH="/var/www/html/public/t3docs"

clone_manual() {
    local repositoryUrl=$1
    local branch=$2
    local manualFolder=$3

    if [[ -d "$TARGET_BASEPATH/$manualFolder" ]]; then
        echo "Manual '$manualFolder' already exists."
    else
        echo "Clone manual '$manualFolder' from '$repositoryUrl' .."
        git clone --branch "$branch" "$repositoryUrl" "$manualFolder"
    fi

    cd "$manualFolder"
    git stash
    git checkout "$branch"
    git pull --rebase
    cd - > /dev/null
}

[[ ! -d "$TARGET_BASEPATH" ]] && mkdir "$TARGET_BASEPATH"
cd "$TARGET_BASEPATH"

clone_manual "git@github.com:TYPO3-Documentation/TYPO3CMS-Guide-Installation" "master" "TYPO3CMS-Guide-Installation"
clone_manual "git@github.com:TYPO3-Documentation/TYPO3CMS-Reference-CoreApi" "master" "TYPO3CMS-Reference-CoreApi"
clone_manual "git@github.com:TYPO3-Documentation/TYPO3CMS-Reference-TCA.git" "master" "TYPO3CMS-Reference-TCA"
clone_manual "git@github.com:TYPO3-Documentation/TYPO3CMS-Reference-TSconfig" "master" "TYPO3CMS-Reference-TSconfig"
clone_manual "git@github.com:TYPO3-Documentation/TYPO3CMS-Tutorial-Editors" "master" "TYPO3CMS-Tutorial-Editors"
clone_manual "git@github.com:TYPO3-Documentation/TYPO3CMS-Tutorial-GettingStarted" "master" "TYPO3CMS-Tutorial-GettingStarted"

cd - > /dev/null
