#!/bin/bash

## Description: Initialize Distributions
## Usage: initialize-distributions
## Example: initialize-distributions

DIST_PATH="/var/www/html/distributions"

initialize-distribution() {
    local distName=$1
    local distPath=$DIST_PATH/$distName
    local dbName=db_$distName

    echo "Initializing $distName"

    composer up -d $distPath --no-install
}

# Install main project in case it has not happened yet
[ -d /var/www/html/vendor ] || composer install -d /var/www/html

composer intitialize-distributions

for dist in $DIST_PATH/*/dist.json
do

  initialize-distribution $(basename $(dirname $dist))

done
