#!/bin/bash

## Description: Init basic screenshots.json inside the web container
## Usage: init-screenshot-json (folder|path)
## Example: "init-screenshot-json My-Manual" or "init-screenshot-json /var/www/html/t3docs/My-Manual"

init_screenshot_json() {
    local manualFolder=${1}
    typo3 screenshots:init $manualFolder
}

init_screenshot_json $@
