#!/bin/bash

## Description: Run Puppeteer with specified file
## Usage: prepare

composer install
npm install

echo "Installing TYPO3"
./vendor/bin/typo3cms install:setup --no-interaction --admin-user-name admin --admin-password demo.typo3

echo "importing database"
./vendor/bin/typo3cms database:import < Install/dump.sql

echo
echo "All done!"
echo "try running \"ddev exec node puppeteer-testscript.js\" and watch folder \"Screenshots/\""
